### ISSUE TITLE
Series vs Location

### ISSUE THREAD

**Issue by djhocking** [Conte-Ecology/conteStreamTemperature_web#14]
What is the difference between `series_id` and `location_id`? There are some cases that I have two `series_id` at the same location on the same date but the temperature values are very slightly different (for example series_id 1480 & 1481 at location 736 on 2007-08-01). There are ~15,000 of these records. Does this mean that there were two separate loggers at the same location on the same day? Should these be considered different locations within the same stream? If they have the same lat and lon should they just be one location?

Basically, when doing the analysis is my unique measurement actually series-location-datetime? If so then should the hierarchy of the model be:

series-location-date (time compressed to daily) within
     - location (I'd probably leave out this level) within
        - featureid (stream reach) within
             - HUC8 (or could do any or multiple HUC nesting)

I had been using measurements within `location_id` as the smallest unit but it seems to have broken some code because there are those multiple values at the same location on the same day.

**Comment by walkerjeffd** [comment]
yes, you can definitely have multiple series per location. think of a series as a deployment, which I would define as a set of continuous values measured by one logger at one location (so within a series, all datetimes should be unique).

some agencies are putting multiple loggers at the same location. I know NOAA has many sites with multiple overlapping loggers because they put one at the bottom of the river, and a second one at the surface (and they also have something called a live car, though I'm not sure what that is exactly). the values of these overlapping loggers are often similar, but I am finding some that go out of water, so the difference can be more than 10 deg between a pair of loggers.

for the examples you mentioned (series_id 1480 and 1481), those are from CTDEEP. based on the files I have, they are at the same location (same lat/lon), whether they are at the exact same spot, I can't say. and they overlap for about 3 months. 

so if you want to have a unique timeseries (i.e. no duplicated dates), then you probably need to go to the series level. 

a potential issue with that is that you could be breaking some time series across years. For example, say CTDEEP puts a logger out for the summer of 2006, and then again for the summer of 2007 at the same location. those would probably be uploaded as separate series. so even though they don't overlap and you might want to concatenate them to have one timeseries spanning 2006-2007. if you nest to the series level then they will be treated independently. i'm not sure if that has an impact on the model, but i imagine it would.

if i were you, I would first compute the daily mean of each series, and then compute the mean of the series daily mean at each location. then you'd have a single timeseries per location (all unique dates). for the most part, i'm guessing the difference would be relatively small (less than a degree), though you'll almost certainly find cases where the daily means between two overlapping series could vary by more than 1 degree. you might then want to screen those out or choose one or the other rather than averaging the two.

we could add constraints to the database that prevent overlapping series, but i think its not uncommon for agencies to have some overlaps as they switch from one logger to another. so if two 6-month deployments overlap by a day or two then only one could be uploaded unless they manually removed the overlap from one of the series. 

and if they do intentionally put two loggers out at the same time, then its not clear which one should be given precedence (e.g. NOAA with bottom/surface loggers). 

so i think it would be better to handle it from our end, but as this goes on I expect the amount of data processing involved will grow significantly. almost every batch of data I've received has its own unique set of oddities (not to mention the fact that almost no one knows whether the timestamps are in EST or EDT, but that shouldn't make a big difference for daily means).

**Comment by djhocking** [comment]
Thanks for all that info Jeff. I'm sure it would have been easier to explain with a call but it's nice to have it here to refer back to and have backed up. 

I think I can use `series_id` as my lowest unit. If I did it would create a hierarchy like:

```
series
---> location
------> reach (feature_id)
---------> HUC8
```

If I did it this way, series would lump the variance due to the particular logger and exact microhabitat location (on the top or bottom, on a side of rock or top, in a shadow, etc.) that iis systematic but sn't accounted for by the covariates or other hierarchical random effects (location, reach, HUC). This way we get information about the systematic differences among series (does a logger at a specific location differ systematically from other loggers at that location) within a reach even though we don't know what causes it (logger inaccuracy, micro-location), then we get information about the variation among locations within a reach and information about variation among reaches within a HUC8.

I will just have to think carefully about where to put the covariates (i.e. at what level do the parameters have different effects - e.g. random slopes).

In theory it would be possible to also include a non-nested, crossed random effect of logger ID but I don't think it's necessary nor do we have the information, so that will just get split between the series effect and the residual error. The year random effects will be included but not nested.

**Comment by djhocking** [comment]
The alternative to this would be to just take the average of any series on a given day at the same location. We would lose the information about the variance (and correlation) of a given logger deployment (series). As we currently have the analysis, location was also averaged (or just first location used) so the finest level of inference was at the reach (featureid) scale. That results in losing information about the variation and correlation within a location and within a reach.

**Comment by djhocking** [comment]
Talked to Ben and will average everything to the reach (`featureid`) level and use the current model for now.
